In [27]:
# Assignment 3 : 
#Task 1
# 1. Write a function to compute 5/0 and use try/except to catch the exceptions

def Compute():
    try:
        x=5/0
    except ArithmeticError as e:
        print("Getting division by zero Error")
        print(e)

Compute()

Getting division by zero Error
division by zero


In [28]:
#Task 1
#2. Implement a Python program to generate all sentences where subject is in ["Americans",
#"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

def BuiltSentences():
    
    subjects=["Americans","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]
    
    for i in subjects:
        for j in verbs:
            for k in objects: 
                print(i+" "+j+" "+k)

BuiltSentences()
    

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [12]:
import numpy as np
x= np.array([1,2,3,5])
n=3
y =np.vander(x,n)
y
#z= np.vander(x, increasing=True)
#z

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [26]:
#Task 2
# Write a function so that the columns of the output matrix are powers of the input vector.
import numpy as np

def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matrix = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matrix = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matrix

print("<-------------output------------------>""\n")

inputvector = np.array([1,2,3,5])
no_col_outputmatrix = 4
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_outputmatrix,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_outputmatrix,True)


print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_outputmatrix,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")



<-------------output------------------>

The input array is: [1 2 3 5] 

Number of columns in output matrix should be: 4 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]] 

